### PR TITLE
Breaks up config

### LINKED ISSUE #4: break commands, jobs and examples into their own files
Per orb best practices, separate each into their own file under the main folders. https://circleci.com/docs/2.0/orbs-best-practices/#maintainability

### PR DESCRIPTION
**Pull request by beatbrot**
Fixes #4

### CODE REVIEW

**Comment by eddiewebb** [comment]
@beatbrot - I made a rather substantial change in the release of 1.0.0. before I realized you had already submitted this change.

Could you merge in the latest from master? There is a new example and I added executors, and removed the docker parameter. See #6

**Comment by beatbrot** [comment]
Sure thing!

**Comment by eddiewebb** [comment]
Dev version of orb available for testing - `eddiewebb/common_tasks@dev:pull/5-d5e10c71ba3d3ef4b4ad3118db46bcbed680abb9`

**Comment by beatbrot** [comment]
Done :) 

Sorry for stupid question, but was [this](https://github.com/eddiewebb/cci-shared-tasks/pull/5#issuecomment-537202022) message a bot or was that actually you trying to help me? 😆

**Comment by eddiewebb** [comment]
Not stupid! The orb release pipeline sent that after successful unit testing. It should also add the final version after merge.

**Review by eddiewebb — APPROVED** [review]

**Comment by eddiewebb** [comment]
*Production* version of orb available for use - `eddiewebb/common_tasks@1.0.1`

**Pull request merged**
